[project]
name = "venmo-auto-cashout"
version = "1.0"
description = "A tool to automatically cash out your Venmo balance"
authors = [
    {name = "Evan Purkhiser", email = "evanpurkhiser@gmail.com"},
]
dependencies = [
    "venmo-api-unofficial @ https://github.com/evanpurkhiser/venmo-api-unofficial/archive/ab3b8c6f9424234c39b5d33ca14c89bda1ceb7c4.tar.gz",
    "sentry-sdk~=1.5",
    "requests~=2.27",
    "pyotp~=2.6",
]
requires-python = ">=3.9"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = "https://github.com/evanpurkhiser/venmo-auto-cashout"

[project.scripts]
venmo-auto-cashout = "venmo_auto_cashout:main"

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool.black]
line-length=100
target-version=['py39']

[tool.isort]
profile = "black"
line_length = 100
lines_between_sections = 1
skip = "migrations"

[tool.pdm]

[tool.pyright]
include = ["venmo_auto_cashout"]
extraPaths = ["__pypackages__/3.9/lib"]
